"""Explicitly opt-in: upload ONE generated PDF, retain it for dashboard review.

Only generated bytes are uploaded. Index refresh still reads the local corpus for
compatibility. No cloud resources are provisioned. Normal discovery skips this
test. To opt in from PowerShell:
    $env:RUN_LIVE_SUPABASE_INGESTION = "1"
    backend/.venv/Scripts/python.exe -m unittest discover -s backend/tests -p test_live_ingestion.py -v
    Remove-Item Env:RUN_LIVE_SUPABASE_INGESTION
"""

import os
from pathlib import Path
import sys
import unittest
from uuid import uuid4

import pymupdf
from fastapi.testclient import TestClient

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.agents.retrieval_agent import RetrievalAgent
from app.core.config import SupabaseConfigurationError, get_settings
from app.core.supabase_client import get_supabase_client
from app.main import app
from app.services.database_service import DatabaseService
from app.services.retrieval_index_service import clear_retrieval_cache, get_retrieval_resources
from app.services.storage_service import RESEARCH_PAPERS_BUCKET, StorageService


@unittest.skipUnless(os.environ.get("RUN_LIVE_SUPABASE_INGESTION") == "1", "Live upload requires explicit opt-in.")
class LiveIngestionTest(unittest.TestCase):
    def test_one_generated_pdf_is_persisted_and_searchable(self):
        try:
            get_settings()
        except SupabaseConfigurationError as error:
            self.skipTest(str(error))

        try:
            client = get_supabase_client()
            bucket = client.storage.get_bucket(RESEARCH_PAPERS_BUCKET)
            if bucket.public:
                self.fail("The research-papers bucket must be private before live upload.")
            if bucket.allowed_mime_types != ["application/pdf"]:
                self.fail("Set the bucket MIME restriction to application/pdf before live upload.")
            if not bucket.file_size_limit or not 0 < bucket.file_size_limit <= 25 * 1024 * 1024:
                self.fail("Set the bucket maximum file size to 25 MB before live upload.")
            # Prove a previously warm index is refreshed, not just first-query loading.
            clear_retrieval_cache()
            get_retrieval_resources()
            marker = "ingestionproof" + uuid4().hex
            with pymupdf.open() as pdf:
                page = pdf.new_page()
                remaining = page.insert_textbox(
                    pymupdf.Rect(50, 50, 550, 200),
                    "Synthetic ingestion test.\n" + marker + "\n"
                    "This original generated fixture tests persistent evidence retrieval.\n"
                    "It contains no third-party research, personal data, or credentials.",
                    fontsize=10,
                )
                self.assertGreaterEqual(remaining, 0, "Synthetic text must fit on the test page.")
                content = pdf.tobytes()
            self.assertLess(len(content), 25_000, "The live fixture must remain small.")
            with TestClient(app) as api:
                response = api.post(
                    "/documents/upload",
                    files={"file": ("synthetic-ingestion-test.pdf", content, "application/pdf")},
                    data={"category": "integration-test", "title": "Generated ingestion test fixture"},
                )
            if response.status_code != 201:
                self.fail(f"Live upload returned HTTP {response.status_code}; request details omitted.")
            uploaded = response.json()["document"]
            print("Live test document retained for review:", uploaded["id"])
            database = DatabaseService(client)
            record = database.get_document(uploaded["id"])
            self.assertIsNotNone(record, "Uploaded metadata must be readable.")
            self.assertEqual(record.status, "indexed")
            self.assertEqual(record.page_count, 1)
            self.assertEqual(record.storage_path, f"documents/{record.id}/synthetic-ingestion-test.pdf")
            chunks = database.get_document_chunks(record.id)
            self.assertEqual(len(chunks), uploaded["chunk_count"])
            self.assertTrue(chunks and all(row.token_count and row.processed_text for row in chunks))
            self.assertTrue(StorageService(client).download_pdf(record.storage_path) == content,
                            "Stored PDF bytes must match the generated upload.")
            result = RetrievalAgent().run(marker)
            self.assertEqual(result["status"], "success")
            self.assertTrue(any(
                row.get("document_id") == str(record.id) and marker in row["text"]
                for row in result["results"]
            ), "The newly uploaded document must be retrievable from the refreshed index.")
            # A fresh process/index must load the persistent rows without uploaded bytes.
            clear_retrieval_cache()
            self.assertTrue(any(
                row.get("document_id") == str(record.id)
                for row in RetrievalAgent().run(marker)["results"]
            ), "Persistent chunks must remain searchable after cache reset.")
            print("Upload, private Storage, metadata, chunks, indexed status, and BM25 retrieval: PASS")
        except self.failureException:
            raise
        except Exception:
            raise self.failureException(
                "Live ingestion verification failed; cloud request details are omitted. "
                "Check the retained test document, project connection, schema, and private bucket."
            ) from None


if __name__ == "__main__":
    unittest.main(verbosity=2)
